apiVersion: apps/v1
kind: Deployment
metadata:
  name: chroma-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chroma-server
  template:
    metadata:
      labels:
        app: chroma-server
    spec:
      containers:
      - name: chroma-server
        image: chromadb/chroma 
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: chroma-data
          mountPath: /chroma/chroma
        env:
        - name: CHROMA_DB_PATH
          value: "/data"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      restartPolicy: Always
      volumes:
      - name: chroma-data
        persistentVolumeClaim:
          claimName: chroma-pvc
