apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: be-chatbot-hpa
  namespace: corellms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: be-chatbot      
  minReplicas: 1          
  maxReplicas: 5           
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 
