apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: corellms
  name: full-access-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "services"]
  verbs: ["create", "get", "list", "watch", "delete", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "watch", "delete", "update"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "get", "list", "watch", "delete", "update"]


